version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code:delegated

  db:
    image: "mysql:5.7"
    ports:
      - "3357:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: uu_code_challenge
      MYSQL_ROOT_PASSWORD: password
      MYSQL_INITDB_SKIP_TZINFO:
